export type SpotType = 'adventure' | 'lodging';
export type Language = 'pt' | 'en';

export const INITIAL_SPOTS = [
  { id: "lumber", name: "Serra da Lumber", lat: -24.2386, lng: -49.2558, visited: false, image: "https://hotelparaiso.wordpress.com/wp-content/uploads/2014/11/serra-da-lumber-itararc3a9-sp-00731.jpg", type: 'adventure' as SpotType, capacity: 200, currentLoad: 45, averageRating: 4.8, cityId: "itarare" },
  { id: "rio_verde", name: "Rio Verde", lat: -24.2512, lng: -49.2014, visited: false, image: "https://www.viagensecaminhos.com/wp-content/uploads/2023/02/rio-verde-itarare-sp.jpg", type: 'adventure' as SpotType, capacity: 150, currentLoad: 120, averageRating: 4.9, cityId: "itarare" },
  { id: "pirituba", name: "Cânion Pirituba", lat: -24.2345, lng: -49.0978, visited: false, image: "https://www.viagensecaminhos.com/wp-content/uploads/2023/01/canion-pirituba.jpg", type: 'adventure' as SpotType, capacity: 300, currentLoad: 280, averageRating: 4.7, cityId: "itarare" },
  { id: "poco_encantado", name: "Poço Encantado", lat: -24.1620, lng: -49.3850, visited: false, image: "https://www.senges.pr.gov.br/portal/NAdmin/_lib/file/imgs_imagem_turismo_det/Poco_Encanto(2).jpg", type: 'adventure' as SpotType, capacity: 80, currentLoad: 25, averageRating: 4.9, cityId: "itarare" },
  { id: "morro_chato", name: "Mirante Morro Chato", lat: -24.2000, lng: -49.3000, visited: false, image: "https://www.viagensecaminhos.com/wp-content/uploads/2023/02/itarare-mirante-morro-chato.jpg", type: 'adventure' as SpotType, capacity: 500, currentLoad: 150, averageRating: 4.6, cityId: "itarare" },
  { id: "hotel_itarare", name: "Hotel Itararé", lat: -24.1100, lng: -49.3300, visited: false, image: "https://acheiitarare.com.br/wp-content/uploads/2020/10/Foto-Fachada-Nova-1024x768.jpeg", type: 'lodging' as SpotType, capacity: 100, currentLoad: 75, averageRating: 4.5, cityId: "itarare" },
  { id: "barreira", name: "Parque da Barreira", lat: -24.1370, lng: -49.3639, visited: false, image: "https://www.senges.pr.gov.br/portal/NAdmin/_lib/file/imgs_imagem_turismo/Gruta_Barreira(1)(6).jpg", type: 'adventure' as SpotType, capacity: 400, currentLoad: 90, averageRating: 4.8, cityId: "itarare" }
];

export const INITIAL_COUPONS = [
  { id: "c_artesao", businessName: "Casa do Artesão", address: "Rua XV de Novembro, 56", discount: "Brinde + 5% OFF", used: false, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmpbLcYBcNqO-dC-5mg6pinV9-6xk3JjRtYQ&s", locked: true, requiresProfile: true, lat: -24.1120, lng: -49.3340, isPremium: true },
  { id: "c_dona_bela", businessName: "Café Dona Bela", address: "Rua São Pedro, 100", discount: "10% OFF no Combo", used: false, image: "https://img3.restaurantguru.com/w550/h367/r674-Dona-Bela-design-2025-09.jpg", locked: true, minAdventureSpots: 1, lat: -24.1110, lng: -49.3320 },
  { id: "c_abati", businessName: "Padaria Abati", address: "Rua XV de Novembro, 12", discount: "15% OFF", used: false, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbgo-KLT8D57-_MTYDXoXLuPq_tVtshcrQCA&s", locked: true, minAdventureSpots: 2, lat: -24.1130, lng: -49.3350 },
  { id: "c_hotel", businessName: "Hotel Itararé", address: "Rua São Pedro, 50", discount: "25% OFF na Diária", used: false, image: "https://acheiitarare.com.br/wp-content/uploads/2020/10/Foto-Fachada-Nova-1024x768.jpeg", locked: true, minAdventureSpots: 3, lat: -24.1100, lng: -49.3300, isPremium: true },
  { id: "c_gourmeteria", businessName: "Gourmeteria", address: "Av. Zeca de Moraes, 120", discount: "25% OFF no Prato Principal", used: false, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7cHNxnpNjUPj8es32NzXgPzG4fv-YccY3Qw&s", locked: true, requiresLodging: true, lat: -24.1150, lng: -49.3370, isPremium: true }
];

export const INITIAL_EVENTS = [
  { id: "festa_sao_pedro", image: "https://picsum.photos/seed/festadesaopetro/800/600" },
  { id: "aniversario_itarare", image: "https://picsum.photos/seed/anivitarare/800/600" }
];

export const EMERGENCY_CONTACTS_DATA = [
  { id: "samu", phone: "192" },
  { id: "bombeiros", phone: "193" },
  { id: "pm", phone: "190" },
  { id: "santacasa", phone: "(15) 3531-8166" },
  { id: "guarda", phone: "(15) 3531-2120" }
];

export const TRANSLATIONS = {
  pt: {
    explore: "Explorar",
    map: "Mapa",
    profile: "Perfil",
    coupons: "Cupons",
    about: "Sobre",
    welcome: "Olá",
    visitor: "Visitante",
    explore_and_win: "Conquiste benefícios explorando Itararé",
    adventure_route: "Turismo de Aventura",
    lodging_route: "Rede Hoteleira",
    adventure: "Natureza",
    lodging: "Estadia",
    win_gift: "Casa do Artesão",
    complete_profile_cta: "Retire seu brinde",
    visited_spots: "Locais Visitados",
    my_wallet: "Meus Benefícios",
    unlocked_rewards: "Cupons Disponíveis",
    reward_redeemed: "Benefício Resgatado!",
    show_to_attendant: "Apresente esta tela no estabelecimento.",
    validate_checkin: "Efetuar Check-in",
    verified_visitor: "Presença Confirmada",
    sos: "Emergência",
    sos_subtitle: "Contatos Úteis",
    events: "Eventos",
    events_subtitle: "Agenda Municipal",
    of: "de",
    empty_wallet: "Nenhum benefício",
    empty_wallet_desc: "Visite os atrativos para desbloquear descontos.",
    expert_tip: "Dica de Viagem",
    expert_tip_text: "O check-in só é liberado quando você está no local físico do atrativo.",
    next_goal: "Próximo Nível",
    checkins: "Check-ins",
    validate_on_site: "Disponível no local",
    gift_unlocked: "Voucher liberado",
    complete_profile_gift: "Complete seu perfil para receber um voucher exclusivo da Casa do Artesão.",
    checkin_complete: "Check-in realizado com sucesso!",
    incorrect_token: "QR Code incorreto para este local.",
    distance_block: "Você precisa estar no local para validar o check-in.",
    available: "Disponível",
    full: "Alta Ocupação",
    satisfaction: "Avaliação",
    view_memories: "Ver Relatos",
    memories_title: "Relatos da Comunidade",
    community_memories: "Experiências Compartilhadas",
    take_photo: "Registrar Foto",
    publish: "Enviar Relato",
    no_memories: "Ainda não há relatos para este local.",
    be_first_memory: "Seja o primeiro a compartilhar sua experiência!",
    experience_placeholder: "Conte como foi sua visita...",
    comment_sent: "Relato enviado!",
    experience_recorded: "Seu registro foi salvo na comunidade.",
    privacy_note: "Seus dados são protegidos pela Lei Geral de Proteção de Dados (LGPD).",
    btn_finish_profile: "Salvar Perfil",
    placeholder_name: "Seu nome",
    placeholder_email: "E-mail para contato",
    placeholder_city: "Sua cidade",
    label_name: "Nome Completo",
    label_email: "E-mail",
    label_city: "Cidade de Origem",
    label_age: "Faixa Etária",
    label_interest: "Interesse Principal",
    label_discovery: "Como conheceu o Itararé Pass?",
    select_placeholder: "Selecione...",
    discovery_placeholder: "Selecione uma opção",
    rule_profile: "Completar Perfil",
    rule_lodging: "Check-in em Hotel Oficial",
    rule_1_adventure: "1 Visita à Natureza",
    rule_2_adventure: "2 Visitas à Natureza",
    rule_3_adventure: "3 Visitas à Natureza",
    missing_points: "Falta {count} visita",
    missing_points_plural: "Faltam {count} visitas",
    redeem_reward: "Usar Benefício",
    coupon_used: "Utilizado",
    locked: "Pendente",
    lumber_name: "Serra da Lumber",
    rio_verde_name: "Rio Verde",
    pirituba_name: "Cânion Pirituba",
    poco_encantado_name: "Poço Encantado",
    morro_chato_name: "Mirante Morro Chato",
    hotel_itarare_name: "Hotel Itararé",
    barreira_name: "Parque da Barreira",
    profile_title: "Meu Perfil",
    profile_subtitle: "Dados do Visitante",
    profile_completed_title: "Perfil Atualizado",
    profile_completed_desc: "Olá, {name}! Seu perfil está pronto.",
    go_to_coupons: "Aproveite seus benefícios na aba de cupons.",
    val_name: "Campo obrigatório",
    val_email: "E-mail inválido",
    val_city: "Informe sua cidade",
    val_age: "Informe sua idade",
    val_interest: "Escolha um interesse",
    val_discovery: "Campo obrigatório",
    val_discovery_other: "Especifique o canal",
    lumber_snippet: "Resquícios da Southern Lumber Company, marco do desenvolvimento regional.",
    rio_verde_snippet: "Águas cristalinas e piscinas naturais esculpidas na rocha.",
    pirituba_snippet: "O maior cânion do estado, com formações areníticas milenares.",
    poco_encantado_snippet: "Uma piscina natural de cor esmeralda no coração da mata.",
    morro_chato_snippet: "Vista panorâmica privilegiada de toda a cadeia de cânions.",
    hotel_itarare_snippet: "Ponto de referência hoteleiro no centro urbano.",
    barreira_snippet: "Trincheiras naturais usadas na Revolução de 1932.",
    view_event_details: "Detalhes do Evento",
    sos_warning: "Use estes contatos apenas em situações reais de emergência.",
    safety_tips_title: "Guia de Segurança",
    tip_1: "Evite trilhas remotas sem acompanhamento.",
    tip_2: "Mantenha-se hidratado e use proteção solar.",
    tip_3: "Preserve a natureza: traga seu lixo de volta.",
    tip_4: "Informe sua localização no hotel ou para familiares.",
    age_18_25: "18 a 25 anos",
    age_26_35: "26 a 35 anos",
    age_36_50: "36 a 50 anos",
    age_50_plus: "Acima de 50 anos",
    interest_nature: "Ecoturismo",
    interest_history: "História",
    interest_gastronomy: "Gastronomia",
    interest_sport: "Esportes",
    source_social: "Redes Sociais",
    source_friends: "Amigos/Família",
    source_google: "Pesquisa Online",
    source_agency: "Agência de Turismo",
    source_other: "Outros",
    label_discovery_other: "Qual canal?",
    placeholder_discovery_other: "Ex: Blog de viagem",
    festa_sao_pedro_title: "Festa de São Pedro",
    festa_sao_pedro_desc: "Tradicional celebração cultural e religiosa da cidade.",
    festa_sao_pedro_date: "Junho",
    festa_sao_pedro_loc: "Praça Central",
    festa_sao_pedro_cat: "Cultura",
    aniversario_itarare_title: "Aniversário de Itararé",
    aniversario_itarare_desc: "Eventos cívicos e shows em comemoração à fundação da cidade.",
    aniversario_itarare_date: "Agosto",
    aniversario_itarare_loc: "Centro",
    aniversario_itarare_cat: "Cívico",
    c_artesao_name: "Casa do Artesão",
    c_artesao_addr: "Centro",
    c_artesao_discount: "Brinde + 5% OFF",
    c_dona_bela_name: "Café Dona Bela",
    c_dona_bela_addr: "Rua São Pedro",
    c_dona_bela_discount: "10% OFF no Combo",
    c_abati_name: "Padaria Abati",
    c_abati_addr: "Rua XV de Novembro",
    c_abati_discount: "15% OFF",
    c_hotel_name: "Hotel Itararé",
    c_hotel_addr: "Rua São Pedro",
    c_hotel_discount: "25% OFF na Diaria",
    c_gourmeteria_name: "Gourmeteria",
    c_gourmeteria_addr: "Av. Zeca de Moraes",
    c_gourmeteria_discount: "25% OFF no Prato Principal",
    samu_name: "SAMU",
    samu_desc: "Emergências Médicas",
    bombeiros_name: "Bombeiros",
    bombeiros_desc: "Resgate e Incêndios",
    pm_name: "Polícia Militar",
    pm_desc: "Segurança Pública",
    santacasa_name: "Santa Casa",
    santacasa_desc: "Hospital e Pronto-Socorro",
    guarda_name: "Guarda Municipal",
    guarda_desc: "Patrimônio e Apoio",
    accessibility: "Acessibilidade",
    accessibility_subtitle: "Turismo Inclusivo",
    interface_size: "Tamanho do Texto",
    real_time_preview: "Prévia",
    example_text: "Texto de exemplo para ajuste",
    normal: "Padrão",
    maximum: "Máximo",
    visual_prefs: "Preferências Visuais",
    high_contrast: "Alto Contraste",
    sun_glare_desc: "Melhor visibilidade sob sol forte",
    dyslexic_font: "Fonte Adaptada",
    adapted_typography: "Tipografia para leitura facilitada",
    audio_assistance: "Descrição por Áudio",
    voice_guide_active: "Narration on",
    voice_guide_desc: "Ouça informações sobre os pontos turísticos.",
    libras_project: "Libras",
    inclusion_itarare: "Projeto de Inclusão",
    libras_desc: "Tradução para a Língua Brasileira de Sinais.",
    apply_adjustments: "Aplicar",
    reset_defaults: "Restaurar Padrões",
    featured_partners: "Estabelecimentos Parceiros",
    premium_badge: "Destaque",
    official_partner: "Parceiro Oficial",
    featured_placeholder_title: "Sua empresa aqui?",
    featured_placeholder_subtitle: "Destaque VIP no app",
    how_to_unlock: "Como funciona o benefício?",
    unlock_guide_title: "Explore e Ganhe",
    unlock_guide_step1: "1. Visite os pontos turísticos oficiais e valide sua presença via GPS e QR Code.",
    unlock_guide_step2: "2. Acumule visitas para desbloquear cupons de desconto no comércio da cidade.",
    unlock_guide_step3: "3. No estabelecimento, mostre seu voucher digital para validação no balcão.",
    unlock_guide_cta: "Entendi, vamos explorar!",
    physical_validation_note: "Validação presencial obrigatória.",
    mission_locked: "Pendente: {req}",
    mission_unlocked: "Disponível para uso",
    rating_saved: "Obrigado por avaliar!",
    rate_experience: "O que achou deste local?",
    login_system_title: "Itararé Pass",
    login_system_subtitle: "Sistema Oficial de Turismo",
    login_tab: "Entrar",
    register_tab: "Criar Conta",
    login_alert_msg: "Se você é novo por aqui, use a aba {tab} para gerar seu passaporte digital.",
    label_password: "Senha",
    btn_access_system: "Acessar Sistema",
    label_profile_type: "Tipo de Perfil",
    select_profile_placeholder: "Selecione seu perfil",
    role_tourist: "Sou Turista",
    role_merchant: "Sou Comerciante / Pousada",
    tourist_signup_gift_note: "Complete os dados abaixo e ganhe o voucher da Casa do Artesão imediatamente!",
    placeholder_name_call: "Como quer ser chamado?",
    placeholder_min_pass: "Mínimo 6 caracteres",
    btn_create_account: "Criar Minha Conta",
    merchant_review_alert: "Contas de parceiros passam por verificação municipal antes da liberação do painel de vendas.",
    restricted_access_admin: "Acesso Restrito para Administradores",
    back_to_portal: "Voltar ao Portal",
    tourist_portal_title: "Portal do Turista",
    merchant_portal_title: "Portal do Parceiro",
    admin_portal_title: "Gestão Gov",
    validate_rewards_subtitle: "Validação de Vendas e Benefícios",
    admin_access_note: "Acesso exclusivo para funcionários da Secretaria de Turismo.",
    label_institutional_email: "E-mail Institucional",
    label_business_name: "Nome da Empresa",
    label_whatsapp: "WhatsApp / Telefone",
    placeholder_whatsapp: "(00) 00000-0000",
    stats_tab: "Estatísticas",
    stats_origin_title: "Origem dos Visitantes",
    stats_interest_title: "Preferências de Turismo",
    stats_growth_title: "Crescimento da Base",
    stats_count: "Quantidade"
  },
  en: {
    explore: "Explore",
    map: "Map",
    profile: "Profile",
    coupons: "Rewards",
    about: "About",
    welcome: "Hi",
    visitor: "Visitor",
    explore_and_win: "Unlock benefits by exploring Itararé",
    adventure_route: "Adventure Tourism",
    lodging_route: "Where to Stay",
    adventure: "Nature",
    lodging: "Stay",
    win_gift: "Artisan House",
    complete_profile_cta: "Get your gift",
    visited_spots: "Places Visited",
    my_wallet: "My Rewards",
    unlocked_rewards: "Available Coupons",
    reward_redeemed: "Reward Redeemed!",
    show_to_attendant: "Show this screen to the staff.",
    validate_checkin: "Check-in",
    verified_visitor: "Visit Confirmed",
    sos: "Emergency",
    sos_subtitle: "Useful Contacts",
    events: "Events",
    events_subtitle: "Official Agenda",
    of: "of",
    empty_wallet: "No rewards yet",
    empty_wallet_desc: "Visit attractions to unlock discounts.",
    expert_tip: "Travel Tip",
    expert_tip_text: "Check-in is only available when you are at the physical location.",
    next_goal: "Next Level",
    checkins: "Check-ins",
    validate_on_site: "Available on site",
    gift_unlocked: "Voucher released",
    complete_profile_gift: "Complete your profile to receive an exclusive Artisan House voucher.",
    checkin_complete: "Check-in successful!",
    incorrect_token: "Invalid QR Code for this location.",
    distance_block: "You must be at the location to validate your check-in.",
    available: "Available",
    full: "High Occupancy",
    satisfaction: "Rating",
    view_memories: "View Reviews",
    memories_title: "Community Reports",
    community_memories: "Shared Experiences",
    take_photo: "Take Photo",
    publish: "Submit Report",
    no_memories: "No reports for this location yet.",
    be_first_memory: "Be the first to share your experience!",
    experience_placeholder: "How was your visit? Share your story...",
    comment_sent: "Report submitted!",
    experience_recorded: "Your entry has been saved to the community.",
    privacy_note: "Your data is protected under LGPD regulations.",
    btn_finish_profile: "Save Profile",
    placeholder_name: "Your name",
    placeholder_email: "Contact email",
    placeholder_city: "Your city",
    label_name: "Full Name",
    label_email: "Email",
    label_city: "Home City",
    label_age: "Age Group",
    label_interest: "Primary Interest",
    label_discovery: "How did you hear about us?",
    select_placeholder: "Select...",
    discovery_placeholder: "Select an option",
    rule_profile: "Complete Profile",
    rule_lodging: "Official Hotel Check-in",
    rule_1_adventure: "1 Nature Visit",
    rule_2_adventure: "2 Nature Visits",
    rule_3_adventure: "3 Nature Visits",
    missing_points: "{count} visit missing",
    missing_points_plural: "{count} visits missing",
    redeem_reward: "Use Reward",
    coupon_used: "Used",
    locked: "Pending",
    lumber_name: "Lumber Ridge",
    rio_verde_name: "Green River",
    pirituba_name: "Pirituba Canyon",
    poco_encantado_name: "Enchanted Well",
    morro_chato_name: "Morro Chato Lookout",
    hotel_itarare_name: "Itararé Hotel",
    barreira_name: "Barreira Park",
    profile_title: "My Profile",
    profile_subtitle: "Visitor Data",
    profile_completed_title: "Profile Updated",
    profile_completed_desc: "Hello, {name}! Your profile is ready.",
    go_to_coupons: "Enjoy your benefits in the rewards tab.",
    val_name: "Required field",
    val_email: "Invalid email",
    val_city: "Required field",
    val_age: "Required field",
    val_interest: "Select an interest",
    val_discovery: "Required field",
    val_discovery_other: "Please specify",
    lumber_snippet: "Southern Lumber Company remains, a landmark of regional development.",
    rio_verde_snippet: "Crystal clear waters and natural rock pools.",
    pirituba_snippet: "The largest canyon in the state, with ancient sandstone formations.",
    poco_encantado_snippet: "An emerald-colored natural pool in the heart of the forest.",
    morro_chato_snippet: "Privileged panoramic view of the entire canyon range.",
    hotel_itarare_snippet: "A landmark hotel in the urban center.",
    barreira_snippet: "Natural trenches used in the 1932 Revolution.",
    view_event_details: "Event Details",
    sos_warning: "Use these contacts only in real emergency situations.",
    safety_tips_title: "Safety Guide",
    tip_1: "Avoid remote trails without guidance.",
    tip_2: "Stay hydrated and use sun protection.",
    tip_3: "Respect nature: bring your trash back.",
    tip_4: "Share your location with your hotel or family.",
    age_18_25: "18 to 25",
    age_26_35: "26 to 35",
    age_36_50: "36 to 50",
    age_50_plus: "Over 50",
    interest_nature: "Ecotourism",
    interest_history: "History",
    interest_gastronomy: "Gastronomy",
    interest_sport: "Sports",
    source_social: "Social Media",
    source_friends: "Friends/Family",
    source_google: "Search Engine",
    source_agency: "Travel Agency",
    source_other: "Other",
    label_discovery_other: "Which one?",
    placeholder_discovery_other: "Ex: Travel blog",
    festa_sao_pedro_title: "St. Peter's Festival",
    festa_sao_pedro_desc: "Traditional cultural and religious celebration.",
    festa_sao_pedro_date: "June",
    festa_sao_pedro_loc: "Central Square",
    festa_sao_pedro_cat: "Culture",
    aniversario_itarare_title: "Itararé Anniversary",
    aniversario_itarare_desc: "Civic events and concerts celebrating the city's foundation.",
    aniversario_itarare_date: "August",
    aniversario_itarare_loc: "Downtown",
    aniversario_itarare_cat: "Civic",
    c_artesao_name: "Artisan House",
    c_artesao_addr: "Downtown",
    c_artesao_discount: "Gift + 5% OFF",
    c_dona_bela_name: "Dona Bela Cafe",
    c_dona_bela_addr: "St. Peter's St",
    c_dona_bela_discount: "10% OFF Combo",
    c_abati_name: "Abati Bakery",
    c_abati_addr: "XV de Novembro St",
    c_abati_discount: "15% OFF",
    c_hotel_name: "Itararé Hotel",
    c_hotel_addr: "St. Peter's St",
    c_hotel_discount: "25% OFF Stay",
    c_gourmeteria_name: "Gourmeteria",
    c_gourmeteria_addr: "Zeca de Moraes Ave",
    c_gourmeteria_discount: "25% OFF Main Course",
    samu_name: "EMS (SAMU)",
    samu_desc: "Medical Emergencies",
    bombeiros_name: "Fire Dept",
    bombeiros_desc: "Rescue and Fire",
    pm_name: "Military Police",
    pm_desc: "Public Safety",
    santacasa_name: "Santa Casa",
    santacasa_desc: "Hospital and ER",
    guarda_name: "Municipal Guard",
    guarda_desc: "Protection and Support",
    accessibility: "Accessibility",
    accessibility_subtitle: "Inclusive Tourism",
    interface_size: "Text Size",
    real_time_preview: "Preview",
    example_text: "Example text for adjustment",
    normal: "Default",
    maximum: "Maximum",
    visual_prefs: "Visual Preferences",
    high_contrast: "High Contrast",
    sun_glare_desc: "Better visibility in bright sun",
    dyslexic_font: "Adapted Font",
    adapted_typography: "Facilitated reading typography",
    audio_assistance: "Audio Description",
    voice_guide_active: "Narration on",
    voice_guide_desc: "Listen to information about tourist spots.",
    libras_project: "Libras",
    inclusion_itarare: "Inclusion Project",
    libras_desc: "Brazilian Sign Language translation.",
    apply_adjustments: "Apply",
    reset_defaults: "Restore Defaults",
    featured_partners: "Partner Businesses",
    premium_badge: "Featured",
    official_partner: "Official Partner",
    featured_placeholder_title: "Your business here?",
    featured_placeholder_subtitle: "VIP highlight in the app",
    how_to_unlock: "How does it work?",
    unlock_guide_title: "Explore and Earn",
    unlock_guide_step1: "1. Visit official spots and validate your presence via GPS and QR Code.",
    unlock_guide_step2: "2. Accumulate visits to unlock discount coupons in the city.",
    unlock_guide_step3: "3. At the business, show your digital voucher for validation.",
    unlock_guide_cta: "Got it, let's explore!",
    physical_validation_note: "On-site validation required.",
    mission_locked: "Pending: {req}",
    mission_unlocked: "Available for use",
    rating_saved: "Thanks for rating!",
    rate_experience: "What did you think of this place?",
    login_system_title: "Itararé Pass",
    login_system_subtitle: "Official Tourism System",
    login_tab: "Login",
    register_tab: "Sign Up",
    login_alert_msg: "If you are new here, use the {tab} tab to generate your digital passport.",
    label_password: "Password",
    btn_access_system: "Access System",
    label_profile_type: "Profile Type",
    select_profile_placeholder: "Select your profile",
    role_tourist: "I am a Tourist",
    role_merchant: "I am a Merchant / Hotel",
    tourist_signup_gift_note: "Complete the details below and unlock the Artisan House voucher right away!",
    placeholder_name_call: "How do you want to be called?",
    placeholder_min_pass: "Minimum 6 characters",
    btn_create_account: "Create My Account",
    merchant_review_alert: "Partner accounts undergo municipal verification before the sales panel is released.",
    restricted_access_admin: "Restricted Access for Administrators",
    back_to_portal: "Back to Portal",
    tourist_portal_title: "Tourist Portal",
    merchant_portal_title: "Merchant Portal",
    admin_portal_title: "Gov Management",
    validate_rewards_subtitle: "Sales and Benefits Validation",
    admin_access_note: "Exclusive access for Tourism Secretariat staff.",
    label_institutional_email: "Institutional Email",
    label_business_name: "Business Name",
    label_whatsapp: "WhatsApp / Phone",
    placeholder_whatsapp: "(00) 00000-0000",
    stats_tab: "Statistics",
    stats_origin_title: "Visitor Origin",
    stats_interest_title: "Tourism Preferences",
    stats_growth_title: "User Base Growth",
    stats_count: "Quantity"
  }
};

